-- KAEL POS Supabase Schema Migration

-- 1. Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  login TEXT NOT NULL UNIQUE,
  pass TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'sotuvchi',
  permissions JSONB DEFAULT '[]'::jsonb
);

-- Insert default admin if not exists
INSERT INTO users (login, pass, name, role, permissions) 
VALUES ('admin', '123', 'Administrator', 'admin', '[]'::jsonb)
ON CONFLICT (login) DO NOTHING;

-- 2. Products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  cost NUMERIC NOT NULL DEFAULT 0,
  stock NUMERIC NOT NULL DEFAULT 0,
  "minStock" NUMERIC NOT NULL DEFAULT 0
);

-- 3. Customers table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  balance NUMERIC NOT NULL DEFAULT 0,
  "tgId" TEXT
);

-- Insert default customer 'Umumiy mijoz' (ID will be generated, but better to enforce id 1 if needed, default is ok)
INSERT INTO customers (id, name, phone, address, balance) 
VALUES (1, 'Umumiy mijoz', '', '', 0)
ON CONFLICT (id) DO NOTHING;

-- 4. Sales table
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  "productId" BIGINT NOT NULL,
  "productName" TEXT NOT NULL,
  "customerId" BIGINT NOT NULL,
  "customerName" TEXT NOT NULL,
  qty NUMERIC NOT NULL DEFAULT 0,
  price NUMERIC NOT NULL DEFAULT 0,
  "unitPrice" NUMERIC NOT NULL DEFAULT 0,
  cost NUMERIC NOT NULL DEFAULT 0,
  discount NUMERIC NOT NULL DEFAULT 0,
  total NUMERIC NOT NULL DEFAULT 0,
  profit NUMERIC NOT NULL DEFAULT 0,
  "paidAmount" NUMERIC NOT NULL DEFAULT 0,
  "debtAmount" NUMERIC NOT NULL DEFAULT 0,
  "payType" TEXT NOT NULL,
  "user" TEXT NOT NULL
);

-- 5. Expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  "categoryLabel" TEXT,
  amount NUMERIC NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  time TEXT,
  "user" TEXT NOT NULL
);

-- 6. Dealers table
CREATE TABLE IF NOT EXISTS dealers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  balance NUMERIC NOT NULL DEFAULT 0
);

-- 7. Dealer Transactions table
CREATE TABLE IF NOT EXISTS dealer_txns (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "dealerId" BIGINT NOT NULL,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  products TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  "user" TEXT NOT NULL
);

-- 8. Activity Log table
CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  "user" TEXT NOT NULL,
  action TEXT NOT NULL
);

-- 9. Settings table (for storing tgBotToken and tgChatId)
CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY DEFAULT 1,
  "tgBotToken" TEXT DEFAULT '',
  "tgChatId" TEXT DEFAULT ''
);

-- Insert initial empty settings row
INSERT INTO settings (id, "tgBotToken", "tgChatId") VALUES (1, '', '') ON CONFLICT (id) DO NOTHING;

-- Setting up Row Level Security (RLS) to be fully open for the anon role for this basic usage
-- Note: In production, consider adding more restrictive policies
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE dealers ENABLE ROW LEVEL SECURITY;
ALTER TABLE dealer_txns ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all actions for everyone" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON sales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON expenses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON dealers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON dealer_txns FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for everyone" ON settings FOR ALL USING (true) WITH CHECK (true);
